### ISSUE TITLE
Fix specs (1)

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb-ruby#7]
```
  1) Unitsdb::Prefix parses the prefix NISTp10_0
     Failure/Error: expect(prefix.to_yaml).to be_yaml_equivalent_to(prefix_yaml)
     
       expected YAML to be equivalent
     
       Diff:
        ---
        base: 10
       -name: ''
        power: 0
       -symbol:
       -  ascii: ''
       -  html: ''
       -  latex: ''
       -  unicode: ''
     # ./spec/unitsdb/prefix_spec.rb:12:in `block (3 levels) in <top (required)>'

  2) Unitsdb::Prefixes parses the prefix collection
     Failure/Error: expect(generated).to eq(raw_string)
     
       expected: "---\nNISTp10_30:\n  name: quetta\n  symbol:\n    ascii: Q\n    html: Q\n    latex: Q\n    unicode: Q...i\n  symbol:\n    ascii: Yi\n    html: Yi\n    latex: Yi\n    unicode: Yi\n  base: 2\n  power: 80\n"
            got: "---\nNISTp10_30:\n  name: quetta\n  symbol:\n    ascii: Q\n    html: Q\n    latex: Q\n    unicode: Q...i\n  symbol:\n    ascii: Yi\n    html: Yi\n    latex: Yi\n    unicode: Yi\n  base: 2\n  power: 80\n"
     
       (compared using ==)
     
       Diff:
       @@ -108,12 +108,6 @@
          base: 10
          power: 1
        NISTp10_0:
       -  name: ''
       -  symbol:
       -    ascii: ''
       -    html: ''
       -    latex: ''
       -    unicode: ''
          base: 10
          power: 0
        NISTp10_-1:
       
     # ./spec/unitsdb/prefixes_spec.rb:14:in `block (2 levels) in <top (required)>'

  3) Unitsdb::Unit parses the unit NISTu144
     Failure/Error: expect(unit.to_yaml).to be_yaml_equivalent_to(unit_yaml)
     
       expected YAML to be equivalent
     
       Diff:
        ---
        dimension_url: "#NISTd33"
        quantity_reference:
        - name: magnetic field
          url: "#NISTq87"
        root: true
        root_units:
          enumerated_root_units:
          - power_denominator: 1
            power_numerator: 1
            unit: oersted
        short: oersted
        unit_name:
        - oersted
        unit_symbols:
        - ascii: Oe
          html: Oe
          id: Oe
          latex: "\\ensuremath{\\mathrm{Oe}}"
          mathml: "<mi mathvariant='normal'>Oe</mi>"
          unicode: Oe
        unit_system:
       -  name: ''
          type: non-SI_acceptable
     # ./spec/unitsdb/unit_spec.rb:12:in `block (3 levels) in <top (required)>'
```

**Comment by ronaldtse** [comment]
## Treatment of `nil` versus `empty string`

For 1, I wonder if `nil` and `empty string` are the same thing.

Certainly this is different from empty:
```yaml
base: 10
symbol:
  ascii: ''
  html: ''
  latex: ''
  unicode: ''
```

This is not the same as:
```yaml
base: 10
symbol:
```

or empty:
```yaml
base: 10
````

Similar issue with 2.

## Unitsdb::Unit parses the unit NISTu144

Original:
```yaml
NISTu144:
  dimension_url: "#NISTd33"
  short: oersted
  root: true
  unit_system:
    type: non-SI_acceptable
    name: ''
  unit_name:
  - oersted
  unit_symbols:
  - id: Oe
    ascii: Oe
    html: Oe
    mathml: "<mi mathvariant='normal'>Oe</mi>"
    latex: "\\ensuremath{\\mathrm{Oe}}"
    unicode: Oe
  root_units:
    enumerated_root_units:
    - unit: oersted
      power_denominator: 1
      power_numerator: 1
  quantity_reference:
  - name: magnetic field
    url: "#NISTq87"
```

Not sure what is different...

Maybe 'unit_system.name' is missing.

I believe it will be fixed by this:
* https://github.com/unitsml/unitsdb/pull/54
